FROM node:18-slim

WORKDIR /app

# Install openssl for Prisma
RUN apt-get update && apt-get install -y openssl

# Copy necessary files
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./
COPY prisma ./prisma
COPY init-prisma.sh ./init-prisma.sh

# Install dependencies
RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm i; \
    else echo "Lockfile not found." && exit 1; \
    fi

# Make the init script executable
RUN chmod +x ./init-prisma.sh

# Run the initialization script
CMD ["./init-prisma.sh"]
