services:
  app:
    container_name: app
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    env_file:
      - .docker.env
    networks:
      - app-network
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    volumes:
      - db:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=therevenantsdb
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db: